# DATABASE CONFIG
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update

# SERVER CONFIG
server.port=${PORT:8080}


# FILE UPLOAD CONFIG
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB








# DATABASE CONFIG

# spring.datasource.url=jdbc:mysql://localhost:3306/doko_xpress
# spring.datasource.username=root
# spring.datasource.password=Inspiron@15

# JPA / HIBERNATE CONFIG

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


# Optional (Only* for performance)
# spring.jpa.open-in-view=false

# SERVER CONFIG

# server.port=8081

# FILE UPLOAD CONFIG

# server.tomcat.max-http-form-post-size=50MB
# spring.servlet.multipart.max-file-size=50MB
# spring.servlet.multipart.max-request-size=50MB